"""数据库迁移：为已有库添加新字段，新库由 schema 文件创建。"""
from __future__ import annotations

import logging

from sqlalchemy import text

from digital_labor.db import get_engine
from digital_labor.settings import settings

logger = logging.getLogger(__name__)

IS_SQLITE = settings.database_url.strip().lower().startswith("sqlite:")


def _run_sqlite_migration(conn, add_col_sql: str, col_name: str) -> None:
    try:
        conn.execute(text(add_col_sql))
        conn.commit()
        logger.info("Migration: added column %s to attendance", col_name)
    except Exception as e:  # noqa: BLE001
        conn.rollback()
        if "duplicate column name" in str(e).lower():
            pass  # 已存在
        else:
            logger.warning("Migration %s: %s", col_name, e)


def _run_pg_migration(conn, sql: str) -> None:
    try:
        conn.execute(text(sql))
        conn.commit()
        logger.info("Migration: %s", sql[:60])
    except Exception as e:  # noqa: BLE001
        logger.warning("Migration: %s", e)


def run_job_title_config_migration() -> None:
    """创建 job_title_config 表（若不存在）。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS job_title_config (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    code TEXT UNIQUE NOT NULL,
                    name TEXT NOT NULL,
                    parent_id INTEGER,
                    sort INTEGER DEFAULT 0,
                    created_at TEXT DEFAULT (CURRENT_TIMESTAMP)
                )
            """))
        else:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS job_title_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    parent_id BIGINT,
                    sort INTEGER DEFAULT 0,
                    created_at TIMESTAMPTZ DEFAULT now()
                )
            """))
        conn.commit()
    logger.info("Migration: job_title_config table ensured")


def run_attendance_overtime_migration() -> None:
    """为 attendance 表添加 overtime_hours、standard_hours 字段（已有则跳过）。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            _run_sqlite_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN overtime_hours REAL",
                "overtime_hours",
            )
            _run_sqlite_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN standard_hours REAL",
                "standard_hours",
            )
        else:
            _run_pg_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN IF NOT EXISTS overtime_hours DOUBLE PRECISION",
            )
            _run_pg_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN IF NOT EXISTS standard_hours DOUBLE PRECISION",
            )


def run_attendance_org_id_index_migration() -> None:
    """P3 性能优化：为 attendance.org_id 添加索引，加速考勤报表按组织筛选。"""
    engine = get_engine()
    with engine.connect() as conn:
        conn.execute(text("CREATE INDEX IF NOT EXISTS idx_attendance_org_id ON attendance(org_id)"))
        conn.commit()
    logger.info("Migration: idx_attendance_org_id index ensured")
