"""数据库迁移：为已有库添加新字段，新库由 schema 文件创建。"""
from __future__ import annotations

import logging

from sqlalchemy import text

from digital_labor.db import get_engine
from digital_labor.settings import settings

logger = logging.getLogger(__name__)

IS_SQLITE = settings.database_url.strip().lower().startswith("sqlite:")


def _run_sqlite_migration(conn, add_col_sql: str, col_name: str) -> None:
    try:
        conn.execute(text(add_col_sql))
        conn.commit()
        logger.info("Migration: added column %s to attendance", col_name)
    except Exception as e:  # noqa: BLE001
        conn.rollback()
        if "duplicate column name" in str(e).lower():
            pass  # 已存在
        else:
            logger.warning("Migration %s: %s", col_name, e)


def _run_pg_migration(conn, sql: str) -> None:
    try:
        conn.execute(text(sql))
        conn.commit()
        logger.info("Migration: %s", sql[:60])
    except Exception as e:  # noqa: BLE001
        logger.warning("Migration: %s", e)


def run_job_title_config_migration() -> None:
    """创建 job_title_config 表（若不存在）。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS job_title_config (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    code TEXT UNIQUE NOT NULL,
                    name TEXT NOT NULL,
                    parent_id INTEGER,
                    sort INTEGER DEFAULT 0,
                    created_at TEXT DEFAULT (CURRENT_TIMESTAMP)
                )
            """))
        else:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS job_title_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    parent_id BIGINT,
                    sort INTEGER DEFAULT 0,
                    created_at TIMESTAMPTZ DEFAULT now()
                )
            """))
        conn.commit()
    logger.info("Migration: job_title_config table ensured")


def run_attendance_overtime_migration() -> None:
    """为 attendance 表添加 overtime_hours、standard_hours 字段（已有则跳过）。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            _run_sqlite_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN overtime_hours REAL",
                "overtime_hours",
            )
            _run_sqlite_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN standard_hours REAL",
                "standard_hours",
            )
        else:
            _run_pg_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN IF NOT EXISTS overtime_hours DOUBLE PRECISION",
            )
            _run_pg_migration(
                conn,
                "ALTER TABLE attendance ADD COLUMN IF NOT EXISTS standard_hours DOUBLE PRECISION",
            )
        conn.commit()
    logger.info("Migration: attendance overtime columns ensured")


def run_role_org_scope_migration() -> None:
    """创建 role_org_scope 表（若不存在），用于存储角色的组织数据范围权限。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS role_org_scope (
                    role_code TEXT NOT NULL,
                    org_id INTEGER NOT NULL,
                    scope_type TEXT NOT NULL DEFAULT 'self',
                    PRIMARY KEY (role_code, org_id)
                )
            """))
        else:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS role_org_scope (
                    role_code TEXT NOT NULL,
                    org_id BIGINT NOT NULL,
                    scope_type TEXT NOT NULL DEFAULT 'self',
                    PRIMARY KEY (role_code, org_id)
                )
            """))
        conn.commit()
    logger.info("Migration: role_org_scope table ensured")


def ensure_user_role_has_export_permission() -> None:
    """为已有 user 角色补全 person:export 权限，避免老库升级后需手动勾选。"""
    engine = get_engine()
    with engine.connect() as conn:
        if IS_SQLITE:
            conn.execute(
                text("INSERT OR IGNORE INTO role_permission (role_code, permission_key) VALUES ('user', 'person:export')")
            )
        else:
            conn.execute(
                text(
                    "INSERT INTO role_permission (role_code, permission_key) VALUES ('user', 'person:export') "
                    "ON CONFLICT (role_code, permission_key) DO NOTHING"
                )
            )
        conn.commit()
    logger.info("Migration: user role person:export ensured")


def run_all_migrations() -> None:
    """运行所有迁移。"""
    run_job_title_config_migration()
    run_attendance_overtime_migration()
    run_role_org_scope_migration()
    ensure_user_role_has_export_permission()
    run_performance_indexes()
    logger.info("All migrations completed")


def run_performance_indexes() -> None:
    """创建性能优化索引（幂等，已存在则跳过）。"""
    engine = get_engine()
    indexes = [
        "CREATE INDEX IF NOT EXISTS idx_person_mobile ON person(mobile)",
        "CREATE INDEX IF NOT EXISTS idx_person_name ON person(name)",
        "CREATE INDEX IF NOT EXISTS idx_person_id_card ON person(id_card)",
        "CREATE INDEX IF NOT EXISTS idx_op_log_created_at ON op_log(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_attendance_org_id ON attendance(org_id)",
        "CREATE INDEX IF NOT EXISTS idx_settlement_status ON settlement(status)",
    ]
    with engine.connect() as conn:
        for idx_sql in indexes:
            try:
                conn.execute(text(idx_sql))
                conn.commit()
                logger.info("Migration: created index - %s", idx_sql.split("ON")[1].strip() if "ON" in idx_sql else idx_sql[:50])
            except Exception as e:  # noqa: BLE001
                logger.debug("Index migration skipped: %s", e)
    logger.info("Migration: performance indexes ensured")