-- Digital-Labor PostgreSQL schema
-- 来源：server/db/schema.js（SQLite）映射到 PostgreSQL
-- 目标：保留各表 id，可在迁移时显式插入 id；后续自增继续写入

BEGIN;

-- 组织
CREATE TABLE IF NOT EXISTS org (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT DEFAULT 0,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  sort INTEGER DEFAULT 0,
  manager TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 管理端用户
CREATE TABLE IF NOT EXISTS "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name TEXT,
  org_id BIGINT,
  role TEXT DEFAULT 'admin',
  enabled INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 人员档案
CREATE TABLE IF NOT EXISTS person (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT,
  work_no TEXT,
  name TEXT NOT NULL,
  id_card TEXT,
  mobile TEXT,
  status TEXT DEFAULT '预注册',
  contract_signed INTEGER DEFAULT 0,
  on_site INTEGER DEFAULT 0,
  auth_review_status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  face_verified INTEGER DEFAULT 0,
  face_verified_at TIMESTAMPTZ,
  face_image_url TEXT,
  bank_card TEXT,
  job_title TEXT,
  work_address TEXT,
  signature_image TEXT,
  password_hash TEXT
);

-- 考勤
CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL,
  org_id BIGINT,
  work_date DATE NOT NULL,
  clock_in TEXT,
  clock_out TEXT,
  hours DOUBLE PRECISION DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT uq_attendance_person_date UNIQUE(person_id, work_date)
);

-- 合同模板
CREATE TABLE IF NOT EXISTS contract_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  file_path TEXT,
  version INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  content TEXT,
  variables TEXT,
  is_visual INTEGER DEFAULT 0
);

-- 模板变量
CREATE TABLE IF NOT EXISTS template_variable (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT,
  name TEXT NOT NULL,
  label TEXT NOT NULL,
  type TEXT DEFAULT 'text',
  options TEXT,
  required INTEGER DEFAULT 0
);

-- 合同实例
CREATE TABLE IF NOT EXISTS contract_instance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT,
  title TEXT NOT NULL,
  person_id BIGINT NOT NULL,
  status TEXT DEFAULT '待签署',
  deadline DATE,
  signed_at TIMESTAMPTZ,
  pdf_path TEXT,
  flow_id TEXT,
  sign_image_snapshot TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 结算单
CREATE TABLE IF NOT EXISTS settlement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_hours DOUBLE PRECISION DEFAULT 0,
  amount_due DOUBLE PRECISION DEFAULT 0,
  amount_paid DOUBLE PRECISION DEFAULT 0,
  status TEXT DEFAULT '待确认',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  confirm_at TIMESTAMPTZ,
  confirm_method TEXT,
  sign_image_snapshot TEXT,
  CONSTRAINT uq_settlement_person_period UNIQUE(person_id, period_start)
);

-- 站内通知
CREATE TABLE IF NOT EXISTS notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 人员证书
CREATE TABLE IF NOT EXISTS person_certificate (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  certificate_no TEXT,
  issue_date DATE,
  expiry_date DATE,
  status TEXT DEFAULT 'valid',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 角色菜单
CREATE TABLE IF NOT EXISTS role_menu (
  role_code TEXT NOT NULL,
  menu_path TEXT NOT NULL,
  PRIMARY KEY (role_code, menu_path)
);

-- 角色按钮权限（Node 代码引用但 SQLite schema 未创建，PG 侧补齐）
CREATE TABLE IF NOT EXISTS role_permission (
  role_code TEXT NOT NULL,
  permission_key TEXT NOT NULL,
  PRIMARY KEY (role_code, permission_key)
);

-- 操作日志
CREATE TABLE IF NOT EXISTS op_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  username TEXT,
  module TEXT,
  action TEXT,
  detail TEXT,
  result TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 机具设备
CREATE TABLE IF NOT EXISTS equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT,
  name TEXT NOT NULL,
  code TEXT,
  status TEXT DEFAULT '正常',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 现场录入日志
CREATE TABLE IF NOT EXISTS site_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id BIGINT,
  user_id BIGINT,
  log_type TEXT NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 工人通知设置（H5 端）
CREATE TABLE IF NOT EXISTS worker_notification_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id BIGINT NOT NULL UNIQUE,
  push_enabled INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_worker_notification_settings_worker_id ON worker_notification_settings(worker_id);

-- 打卡流水
CREATE TABLE IF NOT EXISTS clock_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id BIGINT NOT NULL,
  punch_at TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL,
  source TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 索引（按 Node schema 的 idx_*）
CREATE INDEX IF NOT EXISTS idx_person_org_id ON person(org_id);
CREATE INDEX IF NOT EXISTS idx_person_status ON person(status);
CREATE INDEX IF NOT EXISTS idx_person_on_site ON person(on_site);
CREATE INDEX IF NOT EXISTS idx_person_updated_at ON person(updated_at);
CREATE INDEX IF NOT EXISTS idx_person_job_title ON person(job_title);
CREATE INDEX IF NOT EXISTS idx_attendance_work_date ON attendance(work_date);
CREATE INDEX IF NOT EXISTS idx_attendance_person_id ON attendance(person_id);
CREATE INDEX IF NOT EXISTS idx_attendance_person_work_date ON attendance(person_id, work_date);
CREATE INDEX IF NOT EXISTS idx_contract_instance_status ON contract_instance(status);
CREATE INDEX IF NOT EXISTS idx_contract_instance_person ON contract_instance(person_id);
CREATE INDEX IF NOT EXISTS idx_contract_instance_flow_id ON contract_instance(flow_id);
CREATE INDEX IF NOT EXISTS idx_settlement_person_status ON settlement(person_id, status);
CREATE INDEX IF NOT EXISTS idx_settlement_period ON settlement(period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_notification_person_id ON notification(person_id);
CREATE INDEX IF NOT EXISTS idx_notification_created_at ON notification(created_at);
CREATE INDEX IF NOT EXISTS idx_person_work_no ON person(work_no);
CREATE INDEX IF NOT EXISTS idx_person_face_verified ON person(face_verified);
CREATE INDEX IF NOT EXISTS idx_person_certificate_person_id ON person_certificate(person_id);
CREATE INDEX IF NOT EXISTS idx_equipment_org_id ON equipment(org_id);
CREATE INDEX IF NOT EXISTS idx_equipment_status ON equipment(status);
CREATE INDEX IF NOT EXISTS idx_site_log_org_id ON site_log(org_id);
CREATE INDEX IF NOT EXISTS idx_site_log_created_at ON site_log(created_at);
CREATE INDEX IF NOT EXISTS idx_clock_log_person_id ON clock_log(person_id);
CREATE INDEX IF NOT EXISTS idx_clock_log_punch_at ON clock_log(punch_at);

COMMIT;

